name: build
on:
  push: 
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: pip install flit
      - run: python -m flit build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist
